all backup files edited

diff --git a/retrieve_logs b/retrieve_logs
--- a/retrieve_logs
+++ b/retrieve_logs
@@ -3,9 +3,12 @@
 logs_directory="/opt/logs"
 
 # Check if the user is an owner or admin
-is_admin() {
-    grep -q "^$USER$" admins.txt
-    return $?
+has_permission() {
+    if [ -r "$db" ]  [ -x "$db" ]  id -Gn | grep -qw 'admins.txt'; then
+        return 0  # Return success if any condition is met
+    else
+        return 1  # Return failure if none of the conditions are met
+    fi
 }
 
 # Check if the 'logs' directory exists
@@ -15,7 +18,7 @@ if [ ! -d "$logs_directory" ]; then
 fi
 
 # Check if the user is an owner or admin
-if ! is_admin; then
+if ! has_permission; then
     echo "Permission denied. Only admins and owners can retrieve logs."
     exit 1
 fi
diff --git a/rotate_backups_by_date b/rotate_backups_by_date
--- a/rotate_backups_by_date
+++ b/rotate_backups_by_date
@@ -1,27 +1,20 @@
 #!/bin/bash
 
 backup_type="$1"  # Daily, Weekly, Monthly, Date Specific.
-selected_database="$2"  # Database name
+database_backup_dir="$2"  # Database name
 rotation_limit=5  # Number of backups to keep
 
 # Check if the directory exists
-if [ ! -d "/opt/Backups/$backup_type" ]; then
-    echo "Error: Backup directory '/opt/Backups/$backup_type' not found."
-    exit 1
-fi
-# Check if there are any backup files
-if [ "$(ls -A)" ]; then
-    echo "No previous backup files found. Rotation by date not needed."
-    exit 0
-fi
-# Check if the database directory exists
-if [ ! -d "/opt/Backups/$backup_type/$selected_database" ]; then
-    echo "Error: Database directory '/opt/Backups/$backup_type/$selected_database' not found."
+if [ ! -d "/opt/Backups/$backup_type/$database_backup_dir" ]; then
+    echo "Error: Backup directory '/opt/Backups/$backup_type/$selected_database' not found."
     exit 1
 fi
 
+
 # Change to the backup directory
-cd "/opt/Backups/$backup_type/$selected_database" || exit
+cd "/opt/Backups/$backup_type/$database_backup_dir" || exit
 
 # List all backup files, sort them by modification time, and keep the most recent ones
 ls -t | tail -n +$((rotation_limit + 1)) | xargs rm -f
+
+echo "Rotation based on database date completed successfully"
diff --git a/rotate_backups_by_size b/rotate_backups_by_size
--- a/rotate_backups_by_size
+++ b/rotate_backups_by_size
@@ -1,31 +1,21 @@
 #!/bin/bash
 
 backup_type="$1" # Daily, Weekly, Monthly, Date Specific.
-selected_database="$2"  # Database name
+database_backup_dir="$2" 
 max_size=500  # Maximum backup size in megabytes
 
 # Check if the directory exists
-if [ ! -d "/opt/Backups/$backup_type" ]; then
-    echo "Error: Backup directory '/opt/Backups/$backup_type' not found."
-    exit 1
-fi
-# Check if there are any backup files
-if [ "$(ls -A)" ]; then
-    echo "No previous backup files found. Rotation by size not needed."
-    exit 0
-fi
-# Check if the database directory exists
-if [ ! -d "/opt/Backups/$backup_type/$selected_database" ]; then
-    echo "Error: Database directory '/opt/Backups/$backup_type/$selected_database' not found."
+if [ ! -d "/opt/Backups/$backup_type/$database_backup_dir" ]; then
+    echo "Error: Backup directory '/opt/Backups/$backup_type/$selected_database' not found."
     exit 1
 fi
 
 
 # Change to the backup directory
-cd "/opt/Backups/$backup_type/$selected_database" || exit
+cd "/opt/Backups/$backup_type/$database_backup_dir" || exit
 
 # Calculate the total size of the backup directory in megabytes
-total_size=$(du -smc . | grep -o -E '^[0-9]+')
+total_size=$(du -sm "/opt/Backups/$backup_type/$database_backup_dir" | awk '{print $1}')
 
 # Loop until the total size is below the maximum size
 while [ "$total_size" -gt "$max_size" ]; do
